### ISSUE TITLE
How to modify the code for discrete actions?

### ISSUE THREAD

**Issue by ghost** [ikostrikov/pytorch-trpo#1]
Hi, thanks once again for implementing a really interesting algorithm in PyTorch :+1: ,

I was wondering how to modify the code to be able to use it for environments which require discrete actions, (say `cartpole` as in the other pytorch trpo implementation, or maybe even Atari games)?

**Comment by ikostrikov** [comment]
You can check original Theano code. It supports environments with discrete actions as well so you will be able to see how to modify this code.

**Comment by ghost** [comment]
Thanks a lot for the reply - I'm working on it!

Can I ask what's the advantage of using the conjugate gradients (your implementation) vs finite differences (the other PyTorch implementation)? 

Is using exact conjugate gradients a method of handling high dimensions, that finite difference approximations can't handle? 

I guess conjugate gradients will be more stable, I seem to get a lot of `nan`s in the expected value with the finite difference's in the other implementation?

**Comment by ikostrikov** [comment]
Finite differences are more noisy.
