### ISSUE TITLE
what does volatile=True for?

### ISSUE THREAD

**Issue by dragen1860** [ikostrikov/pytorch-trpo#12]
Dear author:
  I found your code very helpful. However, I have problems trying to read the following code:

https://github.com/ikostrikov/pytorch-trpo/blob/eb26e29ed75b7c7b46b0c717331cc7488ab16b8d/main.py#L111

I wonder the usage of volatile flag. I want to when u  set volatile to True/False.

**Comment by ikostrikov** [comment]
I just doesn't compute gradients when one of the inputs is volatile.

But in the new versions of PyTorch it's deprecated.
