### ISSUE TITLE
Have you tested it on the Atari games?

### ISSUE THREAD

**Issue by onlytailei** [ikostrikov/pytorch-trpo#3]

**Comment by ikostrikov** [comment]
No, only for continuous control. For Atari, I would have to train from states that is much less interesting than training from pixels.

**Comment by onlytailei** [comment]
How is the result in continuous control? you mean mujoco?

**Comment by ikostrikov** [comment]
Yes. I just tried to reproduce results from the original code.

**Comment by onlytailei** [comment]
In the [main.py](https://github.com/ikostrikov/pytorch-trpo/blob/master/main.py)

It seems that line 119 and line 115 always get the same result? Will that lead the important sampling always be one?

And also in line 130, old policy and target policy are always the same. Will that make the kl divergence always be 0?

**Comment by ikostrikov** [comment]
See:
https://github.com/ikostrikov/pytorch-trpo/issues/2

**Comment by onlytailei** [comment]
Thank you !! I understand it!
